#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Shortcuts
alias c="clear"
alias dl="cd ~/Downloads"
alias g="git"
alias h="history"

# Git
alias gl="g l" # git log

# Docker
alias dc="docker-compose"
alias dcps="docker-compose ps"
alias d="docker"
alias dps="docker ps"

colorflag="--color"

# List all files colorized in long format
alias l="ls -lFh ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -lAFh ${colorflag}"

# List only directories
alias ld="ls -lFh ${colorflag} | grep --color=never '^d'"

alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

alias grep="grep --color=auto "

alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# PHP
alias php74='docker run --rm -it --rm --name php74_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.4-cli'
alias php73='docker run --rm -it --rm --name php73_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.3-cli'
alias php72='docker run --rm -it --rm --name php72_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.2-cli'
alias php71='docker run --rm -it --rm --name php71_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.1-cli'
alias php="php74"

# NodeJS
alias node13='docker run --rm -it --rm --name node_13 --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp node:13-alpine'
alias node12='docker run --rm -it --rm --name node_12 --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp node:12-alpine'
alias node10='docker run --rm -it --rm --name node_10 --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp node:10-alpine'
alias node="node13"
