#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Shortcuts
alias c="clear"
alias dl="cd ~/Téléchargements"
alias g="git"
alias h="history"

# Git
alias gl="g l" # git log
alias gp="git pull"
alias gc="git checkout"
alias gb="git branch"

# Docker
alias dc="docker-compose"
alias dcps="docker-compose ps"
alias d="docker"
alias dps="docker ps"

colorflag="--color"

# List all files colorized in long format
alias l="ls -lFh ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -lAFh ${colorflag}"
alias ll="la"

# List only directories
alias ld="ls -lFh ${colorflag} | grep --color=never '^d'"

alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

alias grep="grep --color=auto "

alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ip addr show | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"

# PHP
alias php74='docker run --rm -it --name php74_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.4-cli php'
alias php73='docker run --rm -it --name php73_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.3-cli php'
alias php72='docker run --rm -it --name php72_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.2-cli php'
alias php71='docker run --rm -it --name php71_docker --user ${UID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp php:7.1-cli php'
alias php="php74"

# Composer
alias composer='docker run --rm -it --name composer_docker --user ${UID}:${GID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp composer:latest composer'

# Symfony
alias symfony='docker run --rm -it --name symfony_docker --user ${UID}:${GID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp babeuloula/symfony:latest symfony'

# NodeJS
alias docker_node='docker run --rm -it --name node_14 --user ${UID}:${GID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp node:14-alpine'
alias node14="docker_node node"
alias node12='docker run --rm -it --name node_12 --user ${UID}:${GID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp node:12-alpine node'
alias node10='docker run --rm -it --name node_10 --user ${UID}:${GID} -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp node:10-alpine node'
alias node="node14"

# NPM
alias npm="docker_node npm"

# Hollywood
alias hollywood="docker run --rm -it --name hollywood babeuloula/hollywood:latest hollywood"
