# Homebrew initialization (Apple Silicon and Intel)
if [[ "$(uname -m)" == "arm64" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    eval "$(/usr/local/bin/brew shellenv)"
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix nvm)/nvm.sh" ] && source "$(brew --prefix nvm)/nvm.sh"
[ -s "$(brew --prefix nvm)/etc/bash_completion.d/nvm" ] && source "$(brew --prefix nvm)/etc/bash_completion.d/nvm"

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="babeuloula"

DEFAULT_USER="babeuloula"

setopt correct

plugins=(
    composer
    copyfile
    docker
    docker-compose
    encode64
    extract
    httpie
    sublime
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

export LANG=fr_FR.UTF-8

if [[ -f $HOME/.zsh_profile ]]; then
    source $HOME/.zsh_profile
fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C $(which terraform) terraform

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Utiliser fd au lieu de find (plus rapide et respecte le .gitignore)
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Configuration de l'aperçu (Preview)
# CTRL+T : Aperçu du contenu des fichiers avec bat
export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always --line-range :500 {}'"

# ALT+C : Aperçu de l'arborescence des dossiers avec tree
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

# Style global de l'interface
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --inline-info"