export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="babeuloula"

setopt correct

plugins=(
    command-not-found
    composer
    copyfile
    docker
    docker-compose
    encode64
    extract
    httpie
    sublime
)

source $ZSH/oh-my-zsh.sh

if [[ -f $HOME/.zsh_profile ]]; then
    source $HOME/.zsh_profile
fi
